Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -86,11 +86,12 @@ jobs:
 
     - name: Perform OWASP ZAP Baseline Scan
       run: |
-        docker run --rm --network host \
-          -v ${{ github.workspace }}:/zap/wrk:rw \
-          -t ghcr.io/zaproxy/zaproxy:weekly zap-baseline.py \
-          -t http://localhost:8000 \
-          -r zap-report.html || echo "Have some problems"
+        docker run --rm --network zap_network \
+          -v ${{ github.workspace }}/scripts:/zap/scripts:rw \
+          -t ghcr.io/zaproxy/zaproxy:weekly \
+          python /zap/scripts/zap-baseline.py \
+          -t http://pygoat:8000 \
+          -r /zap/wrk/zap-report.html || echo "Scan failed"
 
     - name: List Files in Workspace (Debugging)
       run: ls -la ${{ github.workspace }}
